In [3]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr2=np.array([[1,2,3,4],[4,5,6,7]])
arr2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [7]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
arr6=np.arange(5,16,2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [11]:
arr7=np.linspace(10,0,10)
arr7

array([10.        ,  8.88888889,  7.77777778,  6.66666667,  5.55555556,
        4.44444444,  3.33333333,  2.22222222,  1.11111111,  0.        ])

In [12]:
arr8=arr7.copy()
arr8

array([10.        ,  8.88888889,  7.77777778,  6.66666667,  5.55555556,
        4.44444444,  3.33333333,  2.22222222,  1.11111111,  0.        ])

In [13]:
arr1

array([1, 2, 3, 4, 5])

In [14]:
arr1.shape

(5,)

In [15]:
arr2.shape

(2, 4)

In [16]:
arr9=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr9

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
arr9.shape

(2, 2, 3)

In [18]:
arr9.ndim

3

In [19]:
arr1.ndim

1

In [20]:
arr1.size

5

In [21]:
arr9.size

12

In [22]:
arr9.itemsize

8

In [23]:
arr8.itemsize

8

In [24]:
arr8.dtype

dtype('float64')

In [25]:
arr9.astype('float')

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]])

In [26]:
lista=range(100)
arr11=np.arange(100)
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
import sys

In [28]:
print (sys.getsizeof(87)*len(lista))
#any integer between 0 to 99


2800


In [29]:
print(arr11.itemsize*arr11.size)

800


In [30]:
import time

In [31]:
x=range(100000)
y=range(100000,200000)

starttime=time.time() 
c=[x+y for x,y in zip(x,y)]

print(time.time()-starttime)



0.007216691970825195


In [32]:
a=np.arange(100000)
b=np.arange(100000,200000)

start_time=time.time()
c=a+b
print(time.time()-start_time)


0.0010445117950439453


In [39]:
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
arr12[2:4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
for i in arr12:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [44]:
for i in np.nditer(arr12):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [45]:
ar1=np.array([1,2,3,4,3,5,6])
ar2=np.array([4,5,6,7,8,9,4])

In [47]:
ar1-ar2

array([-3, -3, -3, -3, -5, -4,  2])

In [48]:
ar1*ar2

array([ 4, 10, 18, 28, 24, 45, 24])

In [50]:
ar1*2

array([ 2,  4,  6,  8,  6, 10, 12])

In [ ]:
ar2>6

array([False, False, False,  True,  True,  True, False])

In [55]:
ar3=np.arange(6).reshape(2,3)
ar4=np.arange(6,12).reshape(3,2)


In [56]:
ar3.dot(ar4)

array([[ 28,  31],
       [100, 112]])

In [57]:
ar4.max()
ar4.min()

np.int64(6)

In [ ]:
ar4.min(axis=1)

array([ 6,  8, 10])

In [59]:
ar4.min(axis=0)

array([6, 7])

In [60]:
ar4.mean()

np.float64(8.5)

In [61]:
ar4.std()

np.float64(1.707825127659933)

In [63]:
np.sin(ar4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [64]:
np.median(ar4)

np.float64(8.5)

In [65]:
np.exp(ar4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [66]:
ar4.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [67]:
ar4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [70]:
ar5=np.arange(12,18).reshape(2,3)
ar5

array([[12, 13, 14],
       [15, 16, 17]])

In [72]:
np.hstack((ar3,ar5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [73]:
np.vstack((ar3,ar5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [77]:
np.hsplit(ar3,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [78]:
ar3

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
np.vsplit(ar3,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]